---
apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: backstage
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: backstage
  ports:
    - name: http-backend
      port: {{ .Values.service.port }}
      targetPort: 7007
      protocol: TCP
