---
# SA `thanos` (receive/storegateway/compactor) — S3 access via EKS Pod Identity
# association (ns/SA thanos/thanos), created by terraform. `thanos-query` has no
# S3 access, so it's a separate SA.
{{- if .Values.receive.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.receive.serviceAccount.name }}
  labels: {{- include "thanos.labels" . | nindent 4 }}
{{- end }}
{{- if .Values.query.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.query.serviceAccount.name }}
  labels: {{- include "thanos.labels" . | nindent 4 }}
{{- end }}
