---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kinetics-inference
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: serve=533267178572.dkr.ecr.us-east-1.amazonaws.com/kinetics-training
    argocd-image-updater.argoproj.io/serve.update-strategy: newest-build
    argocd-image-updater.argoproj.io/serve.allow-tags: regexp:^serve-
    argocd-image-updater.argoproj.io/serve.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/serve.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/write-back-target: helmvalues:/helm/inference-service/values.yaml
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/huzaifa678/Kinetics-Continious-Delivery.git
    targetRevision: main
    path: helm/inference-service
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: inference
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
