---
# Catalog entry (ApplicationSet input data — NOT a k8s manifest). The image update is
# used in the dev environment to automatically update the ArgoCD image in the argocd
# namespace. 
name: argocd-image-updater
namespace: argocd
chartRepoURL: https://argoproj.github.io/argo-helm
chartName: argocd-image-updater
chartVersion: "1.2.2"
