{{- if .Values.kafkaSasl.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.kafkaSasl.secretName }}
  namespace: {{ .Values.kafkaSasl.namespace }}
spec:
  refreshInterval: {{ .Values.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.clusterSecretStore.name }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.kafkaSasl.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.kafkaSasl.passwordProperty }}
      remoteRef:
        key: {{ .Values.kafkaSasl.remoteKey }}
        property: {{ .Values.kafkaSasl.passwordProperty }}
{{- end }}
